### ISSUE TITLE
[Bug] Failing to parse Cargo.toml

### ISSUE THREAD

**Issue by werdahias** [kpcyrd/cargo-debstatus#18]
I'm running c`argo debstatus` against the a newly cloned [popsicle](https://github.com/pop-os/popsicle) repo.
The following error occurs:

```
cargo debstatus
    Updating crates.io index
    Updating git repository `https://github.com/pop-os/dbus-udisks2`
    Updating git repository `https://github.com/ids1024/iso9660-rs`
error: failed to select a version for the requirement `clap = "=4.0.8"`
candidate versions found which didn't match: 3.2.23, 3.2.22, 3.2.21, ...
location searched: crates.io index
required by package `popsicle_cli v1.3.0 (/home/werdahias/popsicle/cli)`
Error: cargo metadata returned exit status: 101
```
This clap version exists: [4.0.8](https://crates.io/crates/clap/4.0.8). I suspect that `cargo debstatus` pulls in the 3.x release track and that causes it to error.

Cheers

**Comment by kpcyrd** [comment]
This looks like the local crates.io index is out of sync, even though it shows `Updating crates.io index` as one of the steps. Can you try running `cargo update` in any project to force an update, then try again?

**Comment by werdahias** [comment]
Hm, I just deleted `.cargo/registry` and `.cargo/.git` and ran cargo update in another directory but the error persists. Prefacing the command with `CARGO_NET_GIT_FETCH_WITH_CLI=true` doesn't work, too.

**Comment by werdahias** [comment]
yeah, semt to be a weird bug
