### ISSUE TITLE
Strage licensing transformation

### ISSUE THREAD

**Issue by pemensik** [kpcyrd/cargo-debstatus#41]
It has been pointed on cargo-rpmstatus cousin of this project. This project has GPL license only included in its repository. But it contains link to https://github.com/sfackler/cargo-tree/, which has MIT or Apache license instead. It can contain parts under several licenses and clearly contains similar parts. How exactly were license transformed from MIT or Apache to GPL? Is there any public documentation, why and how that were done? It seems the code were just relicensed. Were it done legally clear way?

Asking, because we would want project derived from this source as a Fedora package.

**Comment by pemensik** [comment]
Initial code were licensed MIT/Apache right from start, since commit https://github.com/sfackler/cargo-tree/commits/c3423bfb8fe1dde4c0a480b882619fefde6fa12f. This project started with GPLv3 at https://github.com/kpcyrd/cargo-debstatus/commit/936f2c67894479ea12c59b258eda0338bd5b830b, but it clearly shares some code parts. Commit adding license on this project is older than original license addition in cargo-tree, so there were no licensing vacuum to choose desired license. It seems to me at least it need to include license texts also of MIT and Apache license and declare license as ``(MIT or Apache) and GPL-3.0-only``, not just GPLv3.

**Comment by kpcyrd** [comment]
I think your assessment is correct, I have clarified it to

```
(MIT OR Apache-2.0) AND GPL-3.0-or-later
```

in this commit: https://github.com/kpcyrd/cargo-debstatus/commit/ba254ff50afc1c304d93f6f469f5343b7bd0c358
