### ISSUE TITLE
cargo-debstatus fails on itself: invalid serialized PackageId for key `package.dependencies`

### ISSUE THREAD

**Issue by juliangilbey** [kpcyrd/cargo-debstatus#6]
Oh dear!

```
erdos:~/debian/cargo-debstatus (master) $ ~/.cargo/bin/cargo-debstatus debstatus
error: failed to parse lock file at: /home/jdg/debian/cargo-debstatus/Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`
```

This was freshly checked out of github.  Any idea what might be going on here?  It works fine when I apply it to debcargo.

**Comment by kpcyrd** [comment]
There have been changes to the Cargo.lock format recently. This is fixed on master, but I didn't have the time yet to port the code for the `(outdated)` labels yet and I'm not sure if I want to release a new version with this feature missing.

**Comment by juliangilbey** [comment]
Ah, thanks; have you pushed the fix to github though? This error was generated using the latest version on github, commit 6ba99dbddd1fe46d0bba42c38425b18082d4494a

Best wishes!

**Comment by kpcyrd** [comment]
hmm, `cargo run debstatus` is working for me on that commit, which version of cargo are you using and how was it installed?

**Comment by juliangilbey** [comment]
Ah, that was the problem: I was using the version in Debian testing (0.40.0); upgrading to the version in sid fixed it.

Thanks!
